// ── Presets de Negócio ────────────────────────────────────────────────────────
// Cada preset define: tema de cores, textos do Hero, imagens placeholder e nome.
// Ao aplicar um preset, ele preenche tanto o themeProvider quanto o appearanceStore.

export const BUSINESS_PRESETS = [
    {
        id: 'default',
        label: 'Loja Geral',
        emoji: '🛒',
        description: 'Template base. Ideal para lojas de propósito geral.',
        theme: {
            primary:      '#16a34a',
            primaryLight: '#bbf7d0',
            primaryMid:   '#86efac',
            primaryDark:  '#15803d',
            accent:       '#1e293b',
            fontPrimary:  'Outfit',
            borderRadius: '0.5rem',
        },
        appearance: {
            storeName:         'Minha Loja',
            storeSlogan:       'Qualidade e praticidade para o seu dia a dia.',
            heroBadgeLabel:    'NOVIDADE',
            heroBadgeText:     'Frete Grátis em Pedidos Acima de R$ 50!',
            heroHeadline:      'Produtos que você vai amar. Preços que você vai confiar.',
            heroStartingPrice: '29.90',
            heroButtonText:    'COMPRAR AGORA',
            heroCardTitle1:    'Melhores produtos',
            heroCardTitle2:    '20% de desconto',
            heroImage:         'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=300&q=80',
            fontFamily:        'Outfit',
        },
    },
    {
        id: 'kids',
        label: 'Loja Infantil',
        emoji: '👶',
        description: 'Brinquedos, roupas e itens para bebês e crianças.',
        theme: {
            primary:      '#ec4899',
            primaryLight: '#fce7f3',
            primaryMid:   '#f9a8d4',
            primaryDark:  '#be185d',
            accent:       '#7c3aed',
            fontPrimary:  'Nunito',
            borderRadius: '1rem',
        },
        appearance: {
            storeName:         'Baby & Kids Store',
            storeSlogan:       'Tudo para deixar a infância mais feliz!',
            heroBadgeLabel:    'LANÇAMENTO',
            heroBadgeText:     'Novidades para seu pequeno chegaram!',
            heroHeadline:      'Brinquedos e roupas que fazem a infância sorrir.',
            heroStartingPrice: '19.90',
            heroButtonText:    'VER COLEÇÃO',
            heroCardTitle1:    'Brinquedos educativos',
            heroCardTitle2:    'Roupas 0-12 anos',
            heroImage:         'https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=300&q=80',
            fontFamily:        'Nunito',
        },
    },
    {
        id: 'electronics',
        label: 'Eletrônicos',
        emoji: '⚡',
        description: 'Gadgets, smartphones, acessórios e tecnologia.',
        theme: {
            primary:      '#2563eb',
            primaryLight: '#dbeafe',
            primaryMid:   '#93c5fd',
            primaryDark:  '#1d4ed8',
            accent:       '#0f172a',
            fontPrimary:  'Inter',
            borderRadius: '0.375rem',
        },
        appearance: {
            storeName:         'TechZone',
            storeSlogan:       'A tecnologia que você precisa, pelo melhor preço.',
            heroBadgeLabel:    'TECH',
            heroBadgeText:     'Os melhores gadgets com entrega rápida!',
            heroHeadline:      'Gadgets que transformam. Preços que surpreendem.',
            heroStartingPrice: '99.90',
            heroButtonText:    'VER PRODUTOS',
            heroCardTitle1:    'Smartphones top',
            heroCardTitle2:    'Até 30% OFF',
            heroImage:         'https://images.unsplash.com/photo-1498049794561-7780e7231661?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=300&q=80',
            fontFamily:        'Inter',
        },
    },
    {
        id: 'fashion',
        label: 'Moda & Estilo',
        emoji: '👗',
        description: 'Roupas, calçados e acessórios para todos os estilos.',
        theme: {
            primary:      '#7c3aed',
            primaryLight: '#ede9fe',
            primaryMid:   '#c4b5fd',
            primaryDark:  '#6d28d9',
            accent:       '#1e1b4b',
            fontPrimary:  'Raleway',
            borderRadius: '0.25rem',
        },
        appearance: {
            storeName:         'Estilo Único',
            storeSlogan:       'Moda que expressa quem você é.',
            heroBadgeLabel:    'COLEÇÃO',
            heroBadgeText:     'Nova coleção outono/inverno chegou!',
            heroHeadline:      'Vista-se com estilo. Inspire-se a cada look.',
            heroStartingPrice: '49.90',
            heroButtonText:    'EXPLORAR LOOKS',
            heroCardTitle1:    'Tendências 2025',
            heroCardTitle2:    'Frete grátis',
            heroImage:         'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=300&q=80',
            fontFamily:        'Raleway',
        },
    },
    {
        id: 'home',
        label: 'Casa & Decoração',
        emoji: '🏠',
        description: 'Móveis, decoração, utilidades e itens para o lar.',
        theme: {
            primary:      '#d97706',
            primaryLight: '#fef3c7',
            primaryMid:   '#fcd34d',
            primaryDark:  '#b45309',
            accent:       '#292524',
            fontPrimary:  'Merriweather',
            borderRadius: '0.5rem',
        },
        appearance: {
            storeName:         'Casa em Ordem',
            storeSlogan:       'Deixe sua casa do jeito que você sempre quis.',
            heroBadgeLabel:    'DESTAQUE',
            heroBadgeText:     'Transforme sua casa com nossos produtos!',
            heroHeadline:      'Decore com amor. Viva com conforto e beleza.',
            heroStartingPrice: '39.90',
            heroButtonText:    'DECORAR AGORA',
            heroCardTitle1:    'Decoração moderna',
            heroCardTitle2:    'Kits exclusivos',
            heroImage:         'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1540518614846-7eded433c457?w=300&q=80',
            fontFamily:        'Merriweather',
        },
    },
    {
        id: 'natural',
        label: 'Natural & Orgânico',
        emoji: '🌿',
        description: 'Alimentação saudável, cosméticos naturais e bem-estar.',
        theme: {
            primary:      '#0d9488',
            primaryLight: '#ccfbf1',
            primaryMid:   '#5eead4',
            primaryDark:  '#0f766e',
            accent:       '#134e4a',
            fontPrimary:  'Poppins',
            borderRadius: '0.75rem',
        },
        appearance: {
            storeName:         'Terra Viva',
            storeSlogan:       'Cuide de você com o que a natureza oferece.',
            heroBadgeLabel:    'ORGÂNICO',
            heroBadgeText:     'Produtos 100% naturais e sustentáveis!',
            heroHeadline:      'Viva com naturalidade. Cuide com propósito.',
            heroStartingPrice: '24.90',
            heroButtonText:    'CONHECER PRODUTOS',
            heroCardTitle1:    'Cosméticos naturais',
            heroCardTitle2:    'Alimentos orgânicos',
            heroImage:         'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80',
            heroCard1Image:    'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300&q=80',
            heroCard2Image:    'https://images.unsplash.com/photo-1490818387583-1baba5e638af?w=300&q=80',
            fontFamily:        'Poppins',
        },
    },
]
